- id: shed_aurelie_light_timer
  alias: Shed Aurelie light timer
  hide_entity: False
  trigger:
    platform: state
    entity_id: light.hue_iris_aurelie
    from: 'off'
    to: 'on'
    # for:
    #   minutes: 15
    #   # minutes: "{{ states('input_number.shed_aurelie_light_delay') | int }}"
  action:
    - delay: '00:{{ states.input_number.shed_aurelie_light_delay.state | int }}:00'
    - service: homeassistant.turn_off
      entity_id: light.hue_iris_aurelie
    
- id: shed_gaetan_light_timer
  alias: Shed Gaetan light timer
  hide_entity: False
  trigger:
    platform: state
    entity_id: light.hue_iris_gaetan
    from: 'off'
    to: 'on'
    # for:
    #   minutes: 20
    #   # minutes: "{{ states('input_number.shed_gaetan_light_delay') | int }}"
  action:
    - delay: '00:{{ states.input_number.shed_gaetan_light_delay.state | int }}:00'
    - service: homeassistant.turn_off
      entity_id: light.hue_iris_gaetan
