homeassistant: !include homeassistant.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

http: !include http.yaml

# Checks for available updates
updater:

# Discover some devices automatically
discovery: !include discovery.yaml

config:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor: !include sensor.yaml

automation: !include automations.yaml

panel_iframe: !include panel_iframe.yaml

influxdb: !include influxdb.yaml

hue: !include hue.yaml

group: !include group.yaml

media_player: !include media_player.yaml

input_number: !include input_number.yaml
