
- platform: netgear
  host: 192.168.0.2
  port: 5000
  username: !secret device_tracker__netgear__username
  password: !secret device_tracker__netgear__password
  new_device_defaults:
    track_new_devices: True
    hide_if_away: False
  
- platform: ping
  interval_seconds: 30
  consider_home: 1200
  hosts:
    gaetan_iphone: 192.168.0.32
    gaetan_macbookpro: 192.168.0.50
    aurelie_iphone: 192.168.0.31