
- platform: netgear
  host: 192.168.1.2
  username: !secret device_tracker__netgear__username
  password: !secret device_tracker__netgear__password
  new_device_defaults:
    track_new_devices: True
    hide_if_away: False