- platform: kodi
  name: "Home Cinema Salon Kodi"
  host: 192.168.0.22
  #username: gaetan
  #password: !secret media_player__kodi__password

- platform: yamaha_musiccast
  host: 192.168.0.24
  name: "MusicCast Chambre Parentale"

- platform: yamaha_musiccast
  host: 192.168.0.20
  name: "MusicCast Salon"

- platform: emby
  host: stibbons.synology.me
  name: "Emby"
  port: 32492
  ssl: True
  api_key: !secret media_player__emby__api_key

- platform: spotify
  client_id: !secret media_player__spotify__client_id
  client_secret: !secret media_player__spotify__client_secret
  cache_path: /mnt/storage/domotic/homeassistant/tmp/.spotify-token-cache