title: AGS Home

views:
  - title: Example
    id: example
    theme: dark-mode
    cards:
        # The markdown card will render markdown text.
      - type: markdown
        title: Lovelace
        content: >
          Welcome to your **Lovelace UI**.

