title: AGS Home

views:
  - title: Main view
    icon: mdi:home-assistant
    cards:
      - title: Today
        type: entities
        entities:
          - sensor.aurelies_work
          - sensor.gaetans_work
          - sensor.forecast_6h_temperature
          - sensor.forecast_6h_precipitation
