title: AGS Home

resources:
  - url: /local/custom_ui/weather-card.js
    type: js

views:
  - title: Main view
    icon: mdi:home-assistant
    cards:

      - type: "custom:weather-card"
        entity_weather: weather.yweather
        entity_sun: sun.sun

      - title: Today
        type: entities
        entities:
          - sensor.aurelies_work
          - sensor.gaetans_work
          - sensor.forecast_6h_temperature
          - sensor.forecast_6h_precipitation
