input_number:
  shed_gaetan_light_delay:
    name: Delai Extinction Lumiere Gaetan
    icon: mdi:clock
    # initial: 45  # no initial to restore states by recorder
    min: 5
    max: 59
    step: 5
  
  shed_aurelie_light_delay:
    name: Delai Extinction Lumiere Aurelie
    icon: mdi:clock
    # initial: 25  # no initial to restore states by recorder
    min: 5
    max: 59
    step: 5

automation:
  - id: shed_aurelie_light_timer
    alias: Shed Aurelie light timer
    hide_entity: False
    trigger:
      platform: state
      entity_id: light.hue_iris_aurelie
      from: 'off'
      to: 'on'
      # for:
      #   minutes: 15
      #   # minutes: "{{ states('input_number.shed_aurelie_light_delay') | int }}"
    action:
      - delay: '00:{{ states.input_number.shed_aurelie_light_delay.state | int }}:00'
      - service: homeassistant.turn_off
        entity_id: light.hue_iris_aurelie

  - id: shed_gaetan_light_timer
    alias: Shed Gaetan light timer
    hide_entity: False
    trigger:
      platform: state
      entity_id: light.hue_iris_gaetan
      from: 'off'
      to: 'on'
      # for:
      #   minutes: 20
      #   # minutes: "{{ states('input_number.shed_gaetan_light_delay') | int }}"
    action:
      - delay: '00:{{ states.input_number.shed_gaetan_light_delay.state | int }}:00'
      - service: homeassistant.turn_off
        entity_id: light.hue_iris_gaetan


group:
  bedroom_lights:
    name: Bedroom lights
    entities:
      - light.hue_iris_aurelie
      - input_number.shed_aurelie_light_delay
      - light.hue_iris_gaetan
      - input_number.shed_gaetan_light_delay
