input_number:
  gaetan_light_timer_minutes:
    name: Lumiere Gaetan - Minutes
    icon: mdi:clock
    # initial: 45  # no initial to restore states by recorder
    min: 0
    max: 59
    step: 1
  gaetan_light_timer_hours:
    name: Lumiere Gaetan - Heures
    icon: mdi:clock
    # initial: 45  # no initial to restore states by recorder
    min: 0
    max: 23
    step: 1
  
  shed_aurelie_light_delay:
    name: Delai Extinction Lumiere Aurelie
    icon: mdi:clock
    # initial: 25  # no initial to restore states by recorder
    min: 5
    max: 59
    step: 5

automation:
  - id: shed_aurelie_light_timer
    initial_state: 'on'
    alias: Shed Aurelie light timer
    hide_entity: False
    trigger:
      platform: state
      entity_id: light.hue_iris_aurelie
      # from: 'off'
      to: 'on'
      for:
        minutes: 30
        # minutes: "{{ states('input_number.shed_aurelie_light_delay') | int }}"
    # trigger:
    #   - platform: template
    #     value_template: "{% if((as_timestamp(now())-as_timestamp(states.switch.sonoff_room_fan.last_updated)) | int /60) >  states.input_slider.bedroomfan_timer_minutes.state | int + states.input_slider.bedroomfan_timer_hours.state |int * 60 | int and states.switch.sonoff_room_fan.state == 'on' -%}true{% endif %}"
    action:
      - delay: '00:{{ states.input_number.shed_aurelie_light_delay.state | int }}:00'
      - service: homeassistant.turn_off
        entity_id: light.hue_iris_aurelie

  # - id: shed_gaetan_light_timer
  #   alias: Shed Gaetan light timer
  #   hide_entity: False
  #   trigger:
  #     platform: state
  #     entity_id: light.hue_iris_gaetan
  #     to: 'on'
  #     for:
  #       minutes: 45
  #   # trigger:
  #   #   - platform: template
  #   #     value_template: "{% if((as_timestamp(now())-as_timestamp(states.switch.sonoff_room_fan.last_updated)) | int /60) >  states.input_slider.bedroomfan_timer_minutes.state | int + states.input_slider.bedroomfan_timer_hours.state |int * 60 | int and states.switch.sonoff_room_fan.state == 'on' -%}true{% endif %}"
  #   action:
  #     # - delay: '00:{{ states.input_number.shed_gaetan_light_delay.state | int }}:00'
  #     - service: homeassistant.turn_off
  #       entity_id: light.hue_iris_gaetan

recorder:
  include:
    entities:
      - light.hue_iris_aurelie
      - light.hue_iris_gaetan

group:
  bedroom_lights:
    name: Bedroom lights
    control: hidden
    entities:
      - light.hue_iris_aurelie
      - input_number.shed_aurelie_light_delay
      - light.hue_iris_gaetan
    #   - input_number.shed_gaetan_light_delay
