sensor:
  - name: Cabinet UPS
    platform: nut
    host: 192.168.0.10
    port: 3493
    alias: ups
    resources:
      - ups.status.display
      - ups.status
      - ups.load
      - ups.delay.shutdown
      - input.voltage
      - battery.runtime
      - battery.charge
      - battery.charge.low
      - output.voltage

  - platform: dht
    sensor: DHT22
    name: cabinet_dht22
    pin: 13
    monitored_conditions:
      - temperature
      - humidity

homeassistant:
  customize:
    sensor.cabinet_dht22_temperature:
      friendly_name: Cabinet Temperature
    sensor.cabinet_dht22_humidity:
      friendly_name: Cabinet Humidity

group:
  cabinet:
    name: Cabinet information
    entities:
      - sensor.cabinet_ups_status
      - sensor.cabinet_ups_input_voltage
      - sensor.cabinet_ups_battery_runtime
      - sensor.cabinet_ups_battery_charge
      - sensor.cabinet_ups_low_battery_setpoint
      - sensor.cabinet_ups_output_voltage
      - sensor.cabinet_ups_ups_shutdown_delay
      - sensor.rfxcom_cabinet_temperature
      - sensor.cabinet_dht22_temperature
