sensor:
  - name: Cabinet UPS
    platform: nut
    host: 192.168.0.10
    port: 3493
    alias: ups
    resources:
      - ups.status.display
      - ups.status
      - ups.load
      - ups.realpower.nominal
      - input.voltage
      - battery.runtime

group:
  cabinet:
    name: Cabinet information
    entities:
      - sensor.cabinet_ups_status
      - sensor.cabinet_ups_input_voltage
      - sensor.cabinet_ups_battery_runtime
      - sensor.cabinet_ups_load