# Do NOT set initial to have state restaured:
#  https://www.home-assistant.io/components/input_select/#restore-state
input_select:
  climate_season:
    name: Climate Season
    options:
     # 'mode été' or 'hors gel': we are during summer, do not care about heating
     - 'Summer or Frost Protection'
     # 'mode hiver': Optimize temperature to maintain confort at lowest cost 
     - 'Winter'
    icon: mdi:weather-sunset-up

  auto_main_heat:
    name: Climate Control Mode
    options:
    - Not / Applicable
    - Automatic mode change
    - Manual mode change
    icon: mdi:robot
    
  main_heat_mode:
    name: Heat Mode
    options:
    - Not / Applicable
    # 'workweek'
    - Work Week
    # 'Vacance à la maison': vacation at home
    - Vacation at Home
    # 'Vacance hors de la maison': vacation out of home, for more than 3 days
    - Vacation out
    icon: mdi:oil-temperature

automation:
  - alias: set_season_summer
    trigger:
      platform: state
      entity_id: input_select.climate_season
      to: 'Summer or Frost Protection'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.auto_main_heat
          option: "Not / Applicable"
      - service: input_select.select_option
        data:
          entity_id: input_select.main_heat_mode
          option: "Not / Applicable"
  - alias: set_season_winter
    trigger:
      platform: state
      entity_id: input_select.climate_season
      to: 'Winter'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.auto_main_heat
          option: "Automatic mode change"
      - service: input_select.select_option
        data:
          option: "Work Week"
          entity_id: input_select.main_heat_mode
        
group:
  climate_control:
    name: Climate Control
    entities:
      - input_select.climate_season
      - input_select.auto_main_heat
      - input_select.main_heat_mode
