#-------------------------------------------
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# inspired by https://community.home-assistant.io/t/epson-wf-3540-ink-level-monitoring/21813
#-------------------------------------------


#-------------------------------------------
sensor:
  - platform: epsonworkforce
    host: 192.168.0.61
    entity_namespace: epson_et_7750
    monitored_conditions:
      - black
      - photoblack
      - yellow
      - magenta
      - cyan
      - clean


#-------------------------------------------
group:
  epson_printer:
    name: Epson Printer Info
    control: hidden
    entities:
      - sensor.epson_et_7750_ink_level_black
      - sensor.epson_et_7750_ink_level_cyan
      - sensor.epson_et_7750_ink_level_magenta
      - sensor.epson_et_7750_ink_level_yellow
      - sensor.epson_et_7750_ink_level_photo_black
      - sensor.epson_et_7750_clean_level

#-------------------------------------------
homeassistant:
  customize_glob:
    "sensor.epson_et_7750_ink_level_*":
      icon: mdi:cup-water
      hidden: False
      homebridge_hidden: True

##############################################################################
###  Automations - Detect when things are not right. Like any Good Watchdog.
##############################################################################

automation:
  - alias: 'ET-7750 Printer Ink Alert'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id:
          - sensor.epson_et_7750_ink_level_black
          - sensor.epson_et_7750_ink_level_photo_black
          - sensor.epson_et_7750_ink_level_magenta
          - sensor.epson_et_7750_ink_level_yellow
          - sensor.epson_et_7750_ink_level_cyan
        below: 25
    condition:
      condition: time
      weekday:
        - wed
    action:
      - service: persistent_notification.create
        data_template:
          title: Low Ink
          message: "{{ trigger.to_state.attributes.friendly_name }} is at {{ trigger.to_state.state }} "
          notification_id: low-battery-alert
      - service: notify.pushover
        data:
          message: "{{ trigger.to_state.attributes.friendly_name }} is at {{ trigger.to_state.state }} "

  - alias: 'ET-7750 Printer clean Alert'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id:
          - sensor.epson_et_7750_clean_level
        above: 75
    condition:
      condition: time
      weekday:
        - wed
    action:
      - service: persistent_notification.create
        data_template:
          title: clean level
          message: "{{ trigger.to_state.attributes.friendly_name }} is at {{ trigger.to_state.state }} "
          notification_id: low-battery-alert
      - service: notify.pushover
        data:
          message: "{{ trigger.to_state.attributes.friendly_name }} is at {{ trigger.to_state.state }} "

#-------------------------------------------


recorder:
  include:
    entities:
      - device_tracker.epsond373aa
      - sensor.epson_et_7750_ink_level_black
      - sensor.epson_et_7750_ink_level_cyan
      - sensor.epson_et_7750_ink_level_magenta
      - sensor.epson_et_7750_ink_level_yellow
      - sensor.epson_et_7750_ink_level_photo_black
      - sensor.epson_et_7750_clean_level
