automation:

  - alias: Dz to Hass Temp+Humidity
    trigger:
       - platform: mqtt
         topic: 'domoticz/out'
    condition: 
       condition: template
       value_template: '{{ trigger.payload_json.dtype == "Temp + Humidity" }}'
    action:
       - service: mqtt.publish
         data_template:
           topic: 'home/sensors/{{ trigger.payload_json.name | replace(" ", "_") | lower }}/temperature'
           payload_template: '{{ trigger.payload_json.svalue1 }}'
       - service: mqtt.publish
         data_template:
           topic: 'home/sensors/{{ trigger.payload_json.name | replace(" ", "_") | lower }}/humidity'
           payload_template: '{{ trigger.payload_json.svalue2 }}'
       - service: mqtt.publish
         data_template:
           topic: 'home/sensors/{{ trigger.payload_json.name | replace(" ", "_") | lower }}/low_battery'
           payload_template: '{{ trigger.payload_json.svalue3 }}'

  - alias: Dz to Hass General Energy
    trigger:
       - platform: mqtt
         topic: 'domoticz/out'
    condition: 
       condition: template
       value_template: '{{ trigger.payload_json.name == "Consommation Électrique Totale" }}'
    action:
       - service: mqtt.publish
         data_template:
           # kWh
           topic: 'home/sensors/home/electricity/energy'
           payload_template: '{{ trigger.payload_json.svalue1 }}'
       - service: mqtt.publish
         data_template:
           # kWh
           topic: 'home/sensors/home/electricity/total_energy'
           payload_template: '{{ trigger.payload_json.svalue2 }}'
           
  - alias: Dz to Hass General Energy
    trigger:
       - platform: mqtt
         topic: 'domoticz/out'
    condition: 
       condition: template
       value_template: '{{ trigger.payload_json.name == "Consommation Électrique Totale" }}'
    action:
       - service: mqtt.publish
         data_template:
           # kWh
           topic: 'home/sensors/general/electricity/energy'
           payload_template: '{{ trigger.payload_json.svalue1 }}'
       - service: mqtt.publish
         data_template:
           # kWh
           topic: 'home/sensors/general/electricity/total_energy'
           payload_template: '{{ trigger.payload_json.svalue2 }}'

  - alias: Dz to Hass Cabinet Energy
    trigger:
       - platform: mqtt
         topic: 'domoticz/out'
    condition: 
       condition: template
       value_template: '{{ trigger.payload_json.name == "Cabinet Energy" }}'
    action:
       - service: mqtt.publish
         data_template:
           # kWh
           topic: 'home/sensors/cabinet/electricity/energy'
           payload_template: '{{ trigger.payload_json.svalue1 }}'
       - service: mqtt.publish
         data_template:
           # kWh
           topic: 'home/sensors/cabinet/electricity/total_energy'
           payload_template: '{{ trigger.payload_json.svalue2 }}'
           
  - alias: Dz to Hass Home Cinema Energy
    trigger:
       - platform: mqtt
         topic: 'domoticz/out'
    condition: 
       condition: template
       value_template: '{{ trigger.payload_json.name == "Home Cinema Energy" }}'
    action:
       - service: mqtt.publish
         data_template:
           # kWh
           topic: 'home/sensors/homecinema/electricity/energy'
           payload_template: '{{ trigger.payload_json.svalue1 }}'
       - service: mqtt.publish
         data_template:
           # kWh
           topic: 'home/sensors/homecinema/electricity/total_energy'
           payload_template: '{{ trigger.payload_json.svalue2 }}'

  - alias: Dz to Hass Washing Machine Energy
    trigger:
       - platform: mqtt
         topic: 'domoticz/out'
    condition: 
       condition: template
       value_template: '{{ trigger.payload_json.name == "Washing Machine Energy" }}'
    action:
       - service: mqtt.publish
         data_template:
           # kWh
           topic: 'home/sensors/washing-machine/electricity/energy'
           payload_template: '{{ trigger.payload_json.svalue1 }}'
       - service: mqtt.publish
         data_template:
           # kWh
           topic: 'home/sensors/washing-machine/electricity/total_energy'
           payload_template: '{{ trigger.payload_json.svalue2 }}'

  - alias: Dz to Hass Washing Machine Power
    trigger:
       - platform: mqtt
         topic: 'domoticz/out'
    condition: 
       condition: template
       value_template: '{{ trigger.payload_json.name == "Washing Machine Power" }}'
    action:
       - service: mqtt.publish
         data_template:
           # kWh
           topic: 'home/sensors/washing-machine/electricity/power'
           payload_template: '{{ trigger.payload_json.svalue1 }}'

  - id: "publish_temperatures"
    alias: 'Send temperatures to MQTT'
    trigger:
       - platform: state
         entity_id:
          - sensor.rfxcom_bathroom_temperature
          - sensor.rfxcom_cigare_cave_temperature
          - sensor.rfxcom_friend_room_temperature
          - sensor.rfxcom_garage_temperature
          - sensor.rfxcom_kitchen_temperature
          - sensor.rfxcom_living_room_temperature
          - sensor.rfxcom_office_temperature
          - sensor.rfxcom_outside_temperature
          - sensor.rfxcom_parents_room_temperature
          - sensor.rfxcom_upper_floor_corridor_temperature
    action:
      - service: mqtt.publish
        data_template:
          topic: >
            home/sensors/
            {{- trigger.entity_id | 
            replace('sensor.rfxcom_', '') |
            replace('_temperature', '/temperature') | lower }}
          payload_template: >
            {{ states(trigger.entity_id) }}

  - id: "publish_humidity"
    alias: 'Send humidity to MQTT'
    trigger:
       - platform: state
         entity_id:
          - sensor.rfxcom_bathroom_humidity
          - sensor.rfxcom_cigare_cave_humidity
          - sensor.rfxcom_friend_room_humidity
          - sensor.rfxcom_garage_humidity
          - sensor.rfxcom_kitchen_humidity
          - sensor.rfxcom_living_room_humidity
          - sensor.rfxcom_office_humidity
          - sensor.rfxcom_outside_humidity
          - sensor.rfxcom_parents_room_humidity
          - sensor.rfxcom_upper_floor_corridor_humidity
    action:
      - service: mqtt.publish
        data_template:
          topic: >
            home/sensors/
            {{- trigger.entity_id | 
            replace('sensor.rfxcom_', '') |
            replace('_humidity', '/humidity') | lower }}
          payload_template: >
            {{ states(trigger.entity_id) }}
            
           
# influxdb:
#   include:
#     entities:
#       - sensor.rfxcom_bathroom_humidity
#       - sensor.rfxcom_bathroom_temperature
#       - sensor.rfxcom_cigare_cave_humidity
#       - sensor.rfxcom_cigare_cave_temperature
#       - sensor.rfxcom_friend_room_humidity
#       - sensor.rfxcom_friend_room_temperature
#       - sensor.rfxcom_garage_humidity
#       - sensor.rfxcom_garage_temperature
#       - sensor.rfxcom_home_energy_energy_usage
#       - sensor.rfxcom_home_energy_total_usage
#       - sensor.rfxcom_kitchen_humidity
#       - sensor.rfxcom_kitchen_temperature
#       - sensor.rfxcom_living_room_humidity
#       - sensor.rfxcom_living_room_temperature
#       - sensor.rfxcom_office_humidity
#       - sensor.rfxcom_office_temperature
#       - sensor.rfxcom_outside_humidity
#       - sensor.rfxcom_outside_temperature
#       - sensor.rfxcom_parent_room_humidity
#       - sensor.rfxcom_parents_room_temperature
#       - sensor.rfxcom_upper_floor_corridor_humidity
#       - sensor.rfxcom_upper_floor_corridor_temperature

sensor:

  # Add all RFXcom sensors
  - platform: rfxtrx
    automatic_add: True
    entity_namespace: rfxcom
    devices:
      '0a52010fee0101233e0079':
        name: Outside
        data_type:
           - Temperature
           - Humidity
      '0a520115fb0401203f0079':
        name: Cigare Cave
        data_type:
           - Temperature
           - Humidity
      '0a5201f3f00200fe480379':
        name: Friend Room
        data_type:
           - Temperature
           - Humidity
      '0a5202102a070119410079':
        name: Bathroom
        data_type:
           - Temperature
           - Humidity
      '0a5202c3780300fe3f0079':
        name: Parents Room
        data_type:
           - Temperature
           - Humidity
      '0a520212ba04011a3f0079':
        name: Kitchen
        data_type:
           - Temperature
           - Humidity
      '0a520214320801203f0059':
        name: Office
        data_type:
           - Temperature
           - Humidity
      '0a520217ff02013c330079':
        name: Garage
        data_type:
           - Temperature
           - Humidity
      '0a520219730101213d0079':
        name: Living Room
        data_type:
           - Temperature
           - Humidity
      '0a520227ec020114450079':
        name: TV Room
        data_type:
           - Temperature
           - Humidity
      '115a02138f02000000029300005c04035479':
        name: Home
        data_type:
           - Energy usage
           - Total usage

  # Temperatures
  - platform: mqtt
    name: "Temperature Exterieur Maison"
    state_topic: "home/sensors/exterieur_maison/temperature"
    unit_of_measurement: "˚C"

  - platform: mqtt
    name: "Temperature Garage"
    state_topic: "home/sensors/garage/temperature"
    unit_of_measurement: "˚C"

  - platform: mqtt
    name: "Temperature Bureau"
    state_topic: "home/sensors/bureau/temperature"
    unit_of_measurement: "˚C"
  
  - platform: mqtt
    name: "Temperature Chambre Amis"
    state_topic: "home/sensors/chambre_amis/temperature"
    unit_of_measurement: "˚C"
      
  - platform: mqtt
    name: "Temperature Cave Cigare"
    state_topic: "home/sensors/cave_cigare/temperature"
    unit_of_measurement: "˚C"

  - platform: mqtt
    name: "Temperature Couloir Haut"
    state_topic: "home/sensors/couloir_haut/temperature"
    unit_of_measurement: "˚C"

  - platform: mqtt
    name: "Temperature Cuisine"
    state_topic: "home/sensors/cuisine/temperature"
    unit_of_measurement: "˚C"

  - platform: mqtt
    name: "Temperature Salon"
    state_topic: "home/sensors/salon/temperature"
    unit_of_measurement: "˚C"

  - platform: mqtt
    name: "Temperature Chambre Parentale"
    state_topic: "home/sensors/chambre_parentale/temperature"
    unit_of_measurement: "˚C"


  # Humidity
  - platform: mqtt
    name: "Humidity Exterieur Maison"
    state_topic: "home/sensors/exterieur_maison/humidity"
    unit_of_measurement: "%"

  - platform: mqtt
    name: "Humidity Garage"
    state_topic: "home/sensors/garage/humidity"
    unit_of_measurement: "%"

  - platform: mqtt
    name: "Humidity Bureau"
    state_topic: "home/sensors/bureau/humidity"
    unit_of_measurement: "%"
  
  - platform: mqtt
    name: "Humidity Chambre Amis"
    state_topic: "home/sensors/chambre_amis/humidity"
    unit_of_measurement: "%"
      
  - platform: mqtt
    name: "Humidity Cave Cigare"
    state_topic: "home/sensors/cave_cigare/humidity"
    unit_of_measurement: "%"

  - platform: mqtt
    name: "Humidity Couloir Haut"
    state_topic: "home/sensors/couloir_haut/humidity"
    unit_of_measurement: "%"

  - platform: mqtt
    name: "Humidity Cuisine"
    state_topic: "home/sensors/cuisine/humidity"
    unit_of_measurement: "%"

  - platform: mqtt
    name: "Humidity Salon"
    state_topic: "home/sensors/salon/humidity"
    unit_of_measurement: "%"

  - platform: mqtt
    name: "Humidity Chambre Parentale"
    state_topic: "home/sensors/chambre_parentale/humidity"
    unit_of_measurement: "%"

  # Powermeters
  - platform: mqtt
    name: "Home Energy"
    unit_of_measurement: "kWh"
    state_topic: "home/sensors/general/electricity/energy"
    value_template: '{{ value | round(1) }}'

  - platform: mqtt
    name: "Home Cinema Energy"
    unit_of_measurement: "kWh"
    state_topic: "home/sensors/homecinema/electricity/energy"
    value_template: '{{ value | round(1) }}'

  - platform: mqtt
    name: "Cabinet Energy"
    unit_of_measurement: "kWh"
    state_topic: "home/sensors/cabinet/electricity/energy"
    value_template: '{{ value | round(1) }}'
    
  - platform: mqtt
    name: "Washing Machine Energy"
    unit_of_measurement: "kWh"
    state_topic: "home/sensors/washing-machine/electricity/energy"
    value_template: '{{ value | round(1) }}'

  - platform: mqtt
    name: "Washing Machine Power"
    unit_of_measurement: "W"
    state_topic: "home/sensors/washing-machine/electricity/power"
    value_template: '{{ value | round(1) }}'


binary_sensor:

  # Low Battery warning
  - platform: mqtt
    name: "Alerte Batterie Exterieur Maison"
    state_topic: "home/sensors/exterieur_maison/low_battery"
    payload_on: "1"
    payload_off: "0"

  - platform: mqtt
    name: "Alerte Batterie Garage"
    state_topic: "home/sensors/garage/low_battery"
    payload_on: "1"
    payload_off: "0"

  - platform: mqtt
    name: "Alerte Batterie Bureau"
    state_topic: "home/sensors/bureau/low_battery"
    payload_on: "1"
    payload_off: "0"
  
  - platform: mqtt
    name: "Alerte Batterie Chambre Amis"
    state_topic: "home/sensors/chambre_amis/low_battery"
    payload_on: "1"
    payload_off: "0"
      
  - platform: mqtt
    name: "Alerte Batterie Cave Cigare"
    state_topic: "home/sensors/cave_cigare/low_battery"
    payload_on: "1"
    payload_off: "0"

  - platform: mqtt
    name: "Alerte Batterie Couloir Haut"
    state_topic: "home/sensors/couloir_haut/low_battery"
    payload_on: "1"
    payload_off: "0"

  - platform: mqtt
    name: "Alerte Batterie Cuisine"
    state_topic: "home/sensors/cuisine/low_battery"
    payload_on: "1"
    payload_off: "0"

  - platform: mqtt
    name: "Alerte Batterie Salon"
    state_topic: "home/sensors/salon/low_battery"
    payload_on: "1"
    payload_off: "0"

  - platform: mqtt
    name: "Alerte Batterie Chambre Parentale"
    state_topic: "home/sensors/chambre_parentale/low_battery"
    payload_on: "1"
    payload_off: "0"

group:
  home_temperatures:
    name: Home Temperatures
    entities:
      # - sensor.temperature_exterieur_maison
      # - sensor.temperature_chambre_parentale
      # - sensor.temperature_chambre_amis
      # - sensor.temperature_bureau
      # - sensor.temperature_couloir_haut
      # - sensor.temperature_salon
      # - sensor.temperature_cuisine
      # - sensor.temperature_cave_cigare
      # - sensor.temperature_garage
      - sensor.rfxcom_bathroom_temperature
      - sensor.rfxcom_friend_room_temperature
      - sensor.rfxcom_garage_temperature
      - sensor.rfxcom_kitchen_temperature
      - sensor.rfxcom_living_room_temperature
      - sensor.rfxcom_office_temperature
      - sensor.rfxcom_outside_temperature
      - sensor.rfxcom_parents_room_temperature
      - sensor.rfxcom_upper_floor_corridor_temperature

  home_humidity:
    name: Home Humidity
    entities:
      - sensor.rfxcom_kitchen_humidity
      - sensor.rfxcom_parents_room_humidity

  cigare_cave:
    name: Cigare Cave
    entities:
      - sensor.rfxcom_cigare_cave_temperature
      - sensor.rfxcom_cigare_cave_humidity

  home_power:
    name: Home Power
    entities:
      # - sensor.powermeter_general
      - sensor.home_cinema_energy
      - sensor.cabinet_energy
      - sensor.washing_machine_energy
      - sensor.washing_machine_power
      - sensor.rfxcom_home_energy_energy_usage
      - sensor.rfxcom_home_energy_total_usage
      
  sensors_battery_alert:
    name: Alerte Batterie Sondes Temperature
      - binary_sensor.alerte_batterie_bureau
      - binary_sensor.alerte_batterie_cave_cigare
      - binary_sensor.alerte_batterie_chambre_amis
      - binary_sensor.alerte_batterie_chambre_parentale
      - binary_sensor.alerte_batterie_couloir_haut
      - binary_sensor.alerte_batterie_cuisine
      - binary_sensor.alerte_batterie_exterieur_maison
      - binary_sensor.alerte_batterie_garage
      - binary_sensor.alerte_batterie_salon
