sensor:
  - platform: sonarr
    api_key: secret! sensor__sonarr__api_key
    host: 192.168.0.10
    port: 32772
    monitored_conditions:
      - series
      - upcoming
      - diskspace
    days: 2
    include_paths:
      - /series
      - /animes

  - platform: radarr
    api_key: secret! sensor__radarr__api_key
    host: 192.168.0.10
    port: 32773
    days: 2
    include_paths:
      - /movies

  - name: Home Cinema UPS
    platform: nut
    host: 192.168.0.22
    port: 3493
    username: upsmon
    password: ups
    alias: ups
    resources:
      - battery.charge
      - battery.charge.low
      - battery.runtime
      - ups.beeper.status
      - ups.delay.shutdown
      - ups.load
      - ups.status.display
  
  - name: Uptime OSMC
    platform: mqtt
    state_topic: "home/osmc/uptime/sec"
    unit_of_measurement: 'sec'

  - name: Temp OSMC
    platform: mqtt
    state_topic: "home/osmc/cpu/temp"
    unit_of_measurement: '°C'


media_player:
  - platform: kodi
    id: kodi_living_room
    name: "Home Cinema Salon Kodi"
    host: 192.168.0.22
    #username: gaetan
    #password: !secret media_player__kodi__password
  
  - platform: yamaha_musiccast
    id: multicast_parent_bedroom
    host: 192.168.0.24
    name: "MusicCast Chambre Parentale"
  
  - platform: yamaha_musiccast
    id: multicast_living_room
    host: 192.168.0.20
    name: "MusicCast Salon"
  
  - platform: yamaha_musiccast
    id: multicast_bureau
    host: 192.168.0.26
    name: "MusicCast Bureaus"
  
  - platform: emby
    host: stibbons.synology.me
    name: "Emby"
    id: emby
    port: 32492
    ssl: True
    api_key: !secret media_player__emby__api_key


remote:
  - platform: harmony
    name: Harmony Hub Home Cinema
    host: 10.168.0.53

    
group:
  pvr:
    name: Smart PVR
    control: hidden
    entities:
      - sensor.radarr_movies
      - sensor.sonarr_upcoming
      - sensor.sonarr_series
      - sensor.sonarr_diskspace
      - media_player.emby__kodi__osmc_2
      - media_player.home_cinema_salon_kodi

  homecine_network:
    name: Home Cinema Information
    entities:
      - sensor.uptime_osmc
      - sensor.temp_osmc
      - sensor.home_cinema_ups_status
      - sensor.home_cinema_ups_battery_charge
      - sensor.home_cinema_ups_low_battery_setpoint
      - sensor.home_cinema_ups_ups_shutdown_delay
      - sensor.home_cinema_ups_battery_runtime
