automation:

#   - id: "publish_temperatures"
#     initial_state: 'off'
#     alias: 'Send temperatures to MQTT'
#     trigger:
#       - platform: state
#          entity_id:
#           - sensor.rfxcom_bathroom_temperature
#           - sensor.rfxcom_friend_room_temperature
#           - sensor.rfxcom_garage_temperature
#           - sensor.rfxcom_kitchen_temperature
#           - sensor.rfxcom_living_room_temperature
#           - sensor.rfxcom_office_temperature
#           - sensor.rfxcom_outside_temperature
#           - sensor.rfxcom_parents_room_temperature
#           - sensor.rfxcom_cigare_cave_temperature
#     action:
#       - service: mqtt.publish
#         data_template:
#           topic: >
#             home/sensors/
#             {{- trigger.entity_id | 
#             replace('sensor.rfxcom_', '') |
#             replace('_temperature', '/temperature') | lower }}
#           payload_template: >
#             {{ states(trigger.entity_id) }}

#   - id: "publish_humidity"
#     initial_state: 'off'
#     alias: 'Send humidity to MQTT'
#     trigger:
#       - platform: state
#          entity_id:
#           - sensor.rfxcom_bathroom_humidity
#           - sensor.rfxcom_cigare_cave_humidity
#           - sensor.rfxcom_friend_room_humidity
#           - sensor.rfxcom_garage_humidity
#           - sensor.rfxcom_kitchen_humidity
#           - sensor.rfxcom_living_room_humidity
#           - sensor.rfxcom_office_humidity
#           - sensor.rfxcom_outside_humidity
#           - sensor.rfxcom_parents_room_humidity
#           - sensor.rfxcom_cigare_cave_humidity
#     action:
#       - service: mqtt.publish
#         data_template:
#           topic: >
#             home/sensors/
#             {{- trigger.entity_id | 
#             replace('sensor.rfxcom_', '') |
#             replace('_humidity', '/humidity') | lower }}
#           payload_template: >
#             {{ states(trigger.entity_id) }}
            
switch:
  # automatically add DIO switches
  - platform: rfxtrx
    entity_namespace: rfxcom
    automatic_add: True
    devices:
      '0b11000a01c5e36201000070':
        # entity: rfxcom_bathroom_heater_remote
        name: Bathroom Heater Remote
        fire_event: true

sensor:

  # Add all RFXcom sensors
  # They change name after each battery change.
  # To find the new name, note the temperature and humidity and find in the
  # devices page the rfx sensor with this value.
  - platform: rfxtrx
    automatic_add: True
    entity_namespace: rfxcom
    devices:
      '0a520104b101007f4a0369':
        name: Outside
        data_type:
           - Temperature
           - Humidity
      '0a520115fb0401203f0079':
        name: Cigare Cave
        data_type:
           - Temperature
           - Humidity
      '0a520105f40200c9310179':
        name: Friend Room
        data_type:
           - Temperature
           - Humidity
      '0a5202102a070119410079':
        name: Bathroom
        data_type:
           - Temperature
           - Humidity
      '0a52020f710300ef380169':
        name: Parents Room
        data_type:
           - Temperature
           - Humidity
      '0a520212ba04011a3f0079':
        name: Kitchen
        data_type:
           - Temperature
           - Humidity
      '0a520214320801203f0059':
        name: Office
        data_type:
           - Temperature
           - Humidity
      '0a520217ff02013c330079':
        name: Garage
        data_type:
           - Temperature
           - Humidity
      '0a520219730101213d0079':
        name: Living Room
        data_type:
           - Temperature
           - Humidity
      '0a520227ec020114450079':
        name: Cabinet
        data_type:
           - Temperature
           - Humidity
      '115a02038e9200000001a200000179b76479':
        name: Home
        data_type:
           - Energy usage
           - Total usage

  - platform: linky
    username: !secret linky_username
    password: !secret linky_password

  # Temperatures
#   - platform: mqtt
#     name: "Temperature Exterieur Maison"
#     state_topic: "home/sensors/exterieur_maison/temperature"
#     unit_of_measurement: "˚C"

#   - platform: mqtt
#     name: "Temperature Garage"
#     state_topic: "home/sensors/garage/temperature"
#     unit_of_measurement: "˚C"

#   - platform: mqtt
#     name: "Temperature Bureau"
#     state_topic: "home/sensors/bureau/temperature"
#     unit_of_measurement: "˚C"
  
#   - platform: mqtt
#     name: "Temperature Chambre Amis"
#     state_topic: "home/sensors/chambre_amis/temperature"
#     unit_of_measurement: "˚C"
      
#   - platform: mqtt
#     name: "Temperature Cave Cigare"
#     state_topic: "home/sensors/cave_cigare/temperature"
#     unit_of_measurement: "˚C"

#   - platform: mqtt
#     name: "Temperature Couloir Haut"
#     state_topic: "home/sensors/couloir_haut/temperature"
#     unit_of_measurement: "˚C"

#   - platform: mqtt
#     name: "Temperature Cuisine"
#     state_topic: "home/sensors/cuisine/temperature"
#     unit_of_measurement: "˚C"

#   - platform: mqtt
#     name: "Temperature Salon"
#     state_topic: "home/sensors/salon/temperature"
#     unit_of_measurement: "˚C"

#   - platform: mqtt
#     name: "Temperature Chambre Parentale"
#     state_topic: "home/sensors/chambre_parentale/temperature"
#     unit_of_measurement: "˚C"

#   - platform: mqtt
#     name: "Temperature Cabinet"
#     state_topic: "home/sensors/cabinet/temperature"
#     unit_of_measurement: "˚C"


#   # Humidity
#   - platform: mqtt
#     name: "Humidity Exterieur Maison"
#     state_topic: "home/sensors/exterieur_maison/humidity"
#     unit_of_measurement: "%"

#   - platform: mqtt
#     name: "Humidity Garage"
#     state_topic: "home/sensors/garage/humidity"
#     unit_of_measurement: "%"

#   - platform: mqtt
#     name: "Humidity Bureau"
#     state_topic: "home/sensors/bureau/humidity"
#     unit_of_measurement: "%"
  
#   - platform: mqtt
#     name: "Humidity Chambre Amis"
#     state_topic: "home/sensors/chambre_amis/humidity"
#     unit_of_measurement: "%"
      
#   - platform: mqtt
#     name: "Humidity Cave Cigare"
#     state_topic: "home/sensors/cave_cigare/humidity"
#     unit_of_measurement: "%"

#   - platform: mqtt
#     name: "Humidity Couloir Haut"
#     state_topic: "home/sensors/couloir_haut/humidity"
#     unit_of_measurement: "%"

#   - platform: mqtt
#     name: "Humidity Cuisine"
#     state_topic: "home/sensors/cuisine/humidity"
#     unit_of_measurement: "%"

#   - platform: mqtt
#     name: "Humidity Salon"
#     state_topic: "home/sensors/salon/humidity"
#     unit_of_measurement: "%"

#   - platform: mqtt
#     name: "Humidity Chambre Parentale"
#     state_topic: "home/sensors/chambre_parentale/humidity"
#     unit_of_measurement: "%"

#   - platform: mqtt
#     name: "Humidity Cabinet"
#     state_topic: "home/sensors/cabinet/humidity"
#     unit_of_measurement: "%"

  # Powermeters
  # - platform: mqtt
  #   name: "Home Energy"
  #   unit_of_measurement: "kWh"
  #   state_topic: "home/sensors/general/electricity/energy"
  #   value_template: '{{ value | round(1) }}'

  # - platform: mqtt
  #   name: "Home Cinema Energy"
  #   unit_of_measurement: "kWh"
  #   state_topic: "home/sensors/homecinema/electricity/energy"
  #   value_template: '{{ value | round(1) }}'

  # - platform: mqtt
  #   name: "Cabinet Energy"
  #   unit_of_measurement: "kWh"
  #   state_topic: "home/sensors/cabinet/electricity/energy"
  #   value_template: '{{ value | round(1) }}'
    
  # - platform: mqtt
  #   name: "Washing Machine Energy"
  #   unit_of_measurement: "kWh"
  #   state_topic: "home/sensors/washing-machine/electricity/energy"
  #   value_template: '{{ value | round(1) }}'

  # - platform: mqtt
  #   name: "Washing Machine Power"
  #   unit_of_measurement: "W"
  #   state_topic: "home/sensors/washing-machine/electricity/power"
  #   value_template: '{{ value | round(1) }}'

  # SRT321
#   - platform: mqtt
#     name: "Thermostat SetPoint"
#     unit_of_measurement: "˚C"
#     state_topic: "home/sensors/thermostat/setpoint"
#     value_template: '{{ value | round(1) }}'

#   - platform: mqtt
#     name: "Thermostat Battery Level"
#     unit_of_measurement: "%"
#     state_topic: "home/sensors/thermostat/battery/level"
#     value_template: '{{ value | round(1) }}'

binary_sensor:
  - platform: template
    sensors:
      rfxcom_bathroom_battery_alert:
        friendly_name: "Bathroom"
        device_class: battery
        value_template: >-
          {{ states.sensor.rfxcom_bathroom_temperature.attributes.get("Battery numeric", 9) != 9 }}
        icon_template: >
          {% if states.sensor.rfxcom_bathroom_temperature.attributes.get("Battery numeric", 9) | int != 9 %}
            mdi:battery-alert
          {% else %}
            mdi:battery
          {% endif %}
      rfxcom_friend_room_battery_alert:
        friendly_name: "Kid's room"
        device_class: battery
        value_template: >-
          {{ states.sensor.rfxcom_friend_room_temperature.attributes.get("Battery numeric", 9) != 9 }}
        icon_template: >
          {% if states.sensor.rfxcom_friend_room_temperature.attributes.get("Battery numeric", 9) | int != 9 %}
            mdi:battery-alert
          {% else %}
            mdi:battery
          {% endif %}
      rfxcom_garage_battery_alert:
        friendly_name: "Garage"
        device_class: battery
        value_template: >-
          {{ states.sensor.rfxcom_garage_temperature.attributes.get("Battery numeric", 9) != 9 }}
        icon_template: >
          {% if states.sensor.rfxcom_garage_temperature.attributes.get("Battery numeric", 9) | int != 9 %}
            mdi:battery-alert
          {% else %}
            mdi:battery
          {% endif %}
      rfxcom_kitchen_battery_alert:
        friendly_name: "Kitchen"
        device_class: battery
        value_template: >-
          {{ states.sensor.rfxcom_kitchen_temperature.attributes.get("Battery numeric", 9) != 9 }}
        icon_template: >
          {% if states.sensor.rfxcom_kitchen_temperature.attributes.get("Battery numeric", 9) | int != 9 %}
            mdi:battery-alert
          {% else %}
            mdi:battery
          {% endif %}
      rfxcom_living_room_battery_alert:
        friendly_name: "Living room"
        device_class: battery
        value_template: >-
          {{ states.sensor.rfxcom_living_room_temperature.attributes.get("Battery numeric", 9) != 9 }}
        icon_template: >
          {% if states.sensor.rfxcom_living_room_temperature.attributes.get("Battery numeric", 9) | int != 9 %}
            mdi:battery-alert
          {% else %}
            mdi:battery
          {% endif %}
      rfxcom_office_battery_alert:
        friendly_name: "Office"
        device_class: battery
        value_template: >-
          {{ states.sensor.rfxcom_office_temperature.attributes.get("Battery numeric", 9) != 9 }}
        icon_template: >
          {% if states.sensor.rfxcom_office_temperature.attributes.get("Battery numeric", 9) | int != 9 %}
            mdi:battery-alert
          {% else %}
            mdi:battery
          {% endif %}
      rfxcom_outside_battery_alert:
        friendly_name: "Outside"
        device_class: battery
        value_template: >-
          {{ states.sensor.rfxcom_outside_temperature.attributes.get("Battery numeric", 9) != 9 }}
        icon_template: >
          {% if states.sensor.rfxcom_outside_temperature.attributes.get("Battery numeric", 9) | int != 9 %}
            mdi:battery-alert
          {% else %}
            mdi:battery
          {% endif %}
      rfxcom_parents_room_battery_alert:
        friendly_name: "Parent's room"
        device_class: battery
        value_template: >-
          {{ states.sensor.rfxcom_parents_room_temperature.attributes.get("Battery numeric", 9) != 9 }}
        icon_template: >
          {% if states.sensor.rfxcom_parents_room_temperature.attributes.get("Battery numeric", 9) | int != 9 %}
            mdi:battery-alert
          {% else %}
            mdi:battery
          {% endif %}
      rfxcom_cigare_cave_battery_alert:
        friendly_name: "Cigare Cave"
        device_class: battery
        value_template: >-
          {{ states.sensor.rfxcom_cigare_cave_temperature.attributes.get("Battery numeric", 9) != 9 }}
        icon_template: >
          {% if states.sensor.rfxcom_cigare_cave_temperature.attributes.get("Battery numeric", 9) | int != 9 %}
            mdi:battery-alert
          {% else %}
            mdi:battery
          {% endif %}

utility_meter:
  home_energy:
    source: sensor.rfxcom_home_energy_usage
    cycle: monthly

  cabinet_energy:
    source: sensor.cabinet_smart_plug_power
    cycle: monthly

  home_cinema_energy:
    source: sensor.home_cinema_smart_plug_power
    cycle: monthly
    
homeassistant:
  customize:
    climate.thermostat_transmitter_heating:
      friendly_name: "Thermostat"
    switch.boiler_actuator_receiver_switch:
      friendly_name: "Boiler"
    sensor.rfxcom_kitchen_humidity:
      icon: mdi:water-percent
    sensor.rfxcom_parents_room_humidity:
      icon: mdi:water-percent
    sensor.rfxcom_cigare_cave_temperature:
      icon: mdi:water-percent
    sensor.rfxcom_cigare_cave_humidity:
      icon: mdi:water-percent
    sensor.rfxcom_home_energy_usage:
      icon: mdi:power-socket-eu
    sensor.cabinet_smart_plug_power:
      icon: mdi:power-socket-eu
    sensor.washing_machine_smart_plug_power_2:
      icon: mdi:power-socket-eu
    sensor.home_cinema_smart_plug_power:
      icon: mdi:power-socket-eu
    sensor.dark_blue_smart_plug_power:
      icon: mdi:power-socket-eu
    sensor.bathroom_heater_wall_plug_power:
      icon: mdi:power-socket-eu


recorder:
  include:
    entities:
      - sensor.entrance_multisensor_2_humidity
      - sensor.entrance_multisensor_2_temperature
      - binary_sensor.entrance_multisensor_2_sensor
      - sensor.rfxcom_bathroom_temperature
      - sensor.rfxcom_cigare_cave_humidity
      - sensor.rfxcom_cigare_cave_temperature
      - sensor.rfxcom_friend_room_temperature
      - sensor.rfxcom_garage_temperature
      - sensor.rfxcom_home_energy_usage
      - sensor.rfxcom_kitchen_humidity
      - sensor.rfxcom_kitchen_temperature
      - sensor.rfxcom_living_room_temperature
      - sensor.rfxcom_office_temperature
      - sensor.rfxcom_outside_temperature
      - sensor.rfxcom_parents_room_humidity
      - sensor.rfxcom_parents_room_temperature
      - sensor.thermostat_setpoint
      - sensor.thermostat_transmitter_battery_level


group:
  home_smart_switches:
    name: Smart Switches
    entities:
      - switch.rfxcom_bathroom_heater_remote

  home_temperatures:
    name: Home Temperatures
    control: hidden
    entities:
      - sensor.rfxcom_bathroom_temperature
      - sensor.rfxcom_friend_room_temperature
      - sensor.rfxcom_garage_temperature
      - sensor.rfxcom_kitchen_temperature
      - sensor.rfxcom_living_room_temperature
      - sensor.rfxcom_office_temperature
      - sensor.rfxcom_outside_temperature
      - sensor.rfxcom_parents_room_temperature

  home_humidity:
    name: Home Humidity
    control: hidden
    entities:
      - sensor.rfxcom_kitchen_humidity
      - sensor.rfxcom_parents_room_humidity

  cigare_cave:
    name: Cigare Cave
    control: hidden
    entities:
      - sensor.rfxcom_cigare_cave_temperature
      - sensor.rfxcom_cigare_cave_humidity

  home_power:
    name: Home Power Meters
    control: hidden
    entities:
      - sensor.rfxcom_home_energy_usage
      - sensor.cabinet_smart_plug_power
      - sensor.washing_machine_smart_plug_power_2
      - sensor.home_cinema_smart_plug_power
      - sensor.dark_blue_smart_plug_power
      - sensor.bathroom_heater_wall_plug_power
      - switch.dark_blue_smart_plug
      
  sensors_battery_alert:
    name: Rfx Battery States
    control: hidden
    entities:
      - binary_sensor.rfxcom_bathroom_battery_alert
      - binary_sensor.rfxcom_friend_room_battery_alert
      - binary_sensor.rfxcom_garage_battery_alert
      - binary_sensor.rfxcom_kitchen_battery_alert
      - binary_sensor.rfxcom_living_room_battery_alert
      - binary_sensor.rfxcom_office_battery_alert
      - binary_sensor.rfxcom_outside_battery_alert
      - binary_sensor.rfxcom_parents_room_battery_alert
      - binary_sensor.rfxcom_cigare_cave_battery_alert
