binary_sensor:
  - platform: iss

camera:
  - platform: generic
    name: ISS
    still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.binary_sensor.iss.attributes.lat }},{{ states.binary_sensor.iss.attributes.long }}&zoom=5&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.binary_sensor.iss.attributes.lat }},{{ states.binary_sensor.iss.attributes.long }}
    limit_refetch_to_url_change: true

sensor:
  - platform: template
    sensors:
      iss_next_rise:
        value_template: '{% set nextrise = as_timestamp(states.binary_sensor.iss.attributes.next_rise) | timestamp_custom("%a %d at %H:%M") %} {{ nextrise }}'
        friendly_name: "Next Visible"

group:
  iss:
    name: International Space Station
    entities:
      - sensor.iss_next_rise
      - camera.iss
      - binary_sensor.iss
      
