#-------------------------------------------
#  Network Related Packages
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
#-------------------------------------------

#-------------------------------------------
sensor:
  - platform: speedtest
    minute: 30
    hour:
      - 0
      - 6
      - 12
      - 18
    monitored_conditions:
      - download
      - upload
  
  - platform: rest
    scan_interval: 86400
    resource: http://ip.jsontest.com
    name: External IP
    value_template: '{{ value_json.ip }}'

  - platform: iperf3
    name: Local Speed
    host: 192.168.0.10
    port: 5201
    scan_interval: 10800  # 3 hours
    monitored_conditions:
      - download
      - upload

  - platform: iperf3
    # Test connection with OSMC, ensure the network is always up
    name: Local Speed
    host: 192.168.0.22
    port: 5201
    scan_interval: 86400  # 24 hours
    monitored_conditions:
      - download
      - upload

  - platform: cert_expiry
    alias: 'Expiration certificat stibbons.synology.me'
    entity_namespace: stibbons_synology_me
    host: stibbons.synology.me
    port: 32483

device_tracker:

  - platform: netgear
    host: !secret device_tracker__netgear__host
    username: admin
    password: !secret device_tracker__netgear__password

  # - platform: ddwrt
  #   host: !secret device_tracker__dd_wrt__host
  #   username: !secret device_tracker__dd_wrt__username
  #   password: !secret device_tracker__dd_wrt__password
  #   new_device_defaults:
  #     track_new_devices: True
  #     hide_if_away: False
    
  # - platform: tomato
  #   host: !secret device_tracker__tomato__host
  #   username: !secret device_tracker__tomato__username
  #   password: !secret device_tracker__tomato__password
  #   http_id: !secret device_tracker__tomato__http_id
  #   new_device_defaults:
  #     track_new_devices: True
  #     hide_if_away: False

  - platform: ping
    interval_seconds: 30
    consider_home: 1200
    hosts:
      gaetan_iphone: 192.168.0.32
      gaetan_macbookpro: 192.168.0.50
      aurelie_iphone: 192.168.0.31
  
  - platform: nmap_tracker
    hosts: 192.168.0.0/24
    home_interval: 30

homeassistant:
  customize:
    sensor.download_192168010:
      friendly_name: Local Download Speed
    sensor.upload_192168010:
      friendly_name: Local Upload Speed
    sensor.download_192168022:
      friendly_name: OSMC Download Speed
    sensor.upload_192168022:
      friendly_name: OSMC Upload Speed

input_boolean:
  update_speedtest:
    name: Update Speedtest
    initial: off
    icon: mdi:refresh

automation:
  - alias: 'Update Speedtest'
    trigger:
      - platform: state
        entity_id: input_boolean.update_speedtest
        to: 'on'
        from: 'off'
    action:
      - service: sensor.iperf3_update
      - service: input_boolean.turn_off
        entity_id: input_boolean.update_speedtest

group:
  network:
    name: Network
    entities:
      - sensor.external_ip
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.download_192168010
      - sensor.upload_192168010
      - sensor.download_192168022
      - sensor.upload_192168022
      - input_boolean.update_speedtest
      - sensor.stibbons_synology_me_ssl_certificate_expiry
