#-------------------------------------------
#  PiHole ad Blocking Related Packages
#
# See also:
#  https://github.com/Norien/Home-Assistant-Config/blob/624a59ebf45915f7e9a60853a3a7ea084175f4d3/packages/pihole.yaml
#-------------------------------------------
homeassistant:
  customize:
    sensor.pi_hole_version:
      friendly_name: Pi-Hole
      entity_picture: /local/custom_icons/pihole.png

    sensor.pi_hole_ads_percentage_today:
      friendly_name: Percentage of Ad Traffic Blocked
      unit_of_measurement: '%'
      icon: mdi:ticket-percent

    sensor.pi_hole_domains_being_blocked:
      friendly_name: Total Domains Blocking
      icon: mdi:do-not-disturb

    sensor.pi_hole_dns_unique_clients:
      friendly_name: Unique Clients
      icon: mdi:desktop-classic

    sensor.pi_hole_ads_blocked_today:
      friendly_name: Ads Blocked Today
      icon: mdi:do-not-disturb

    sensor.pi_hole_dns_queries_today:
      friendly_name: DNS Queries Today
      icon: mdi:note-text

    # sensor.carlopihole:
    #   friendly_name: Pi Hole Server
    #   icon: mdi:filter-variant

    switch.pihole_temp_disable:
      friendly_name: "Temp Disable"

    group.pihole:
      homebridge_hidden: true
#-------------------------------------------
sensor:
  - platform: pi_hole
    host: 192.168.0.5
    name: Pi Hole
    monitored_conditions:
      - dns_queries_today
      - ads_blocked_today
      - ads_percentage_today
      - ads_blocked_today
      - unique_clients

# Pi-Hole switch
switch:
  - platform: command_line
    switches:
      pi_hole_temp_disable:
        command_on: "curl -X GET 'http://192.168.0.5/admin/api.php?enable&auth='"
        command_off: "curl -X GET 'http://192.168.0.5/admin/api.php?disable=3600&auth='"

#-------------------------------------------
group:
  pihole:
    name: Pi-Hole (ad-blocker)
    entities:
      # - sensor.carlopihole
      - sensor.pi_hole_version
      - sensor.pi_hole_dns_unique_clients
      - sensor.pi_hole_dns_queries_today
      - sensor.pi_hole_ads_blocked_today
      - sensor.pi_hole_ads_percentage_today
      - sensor.pi_hole_ads_percentage_blocked_today
      - switch.pi_hole_temp_disable
#-------------------------------------------
panel_iframe:
  pihole:
    title: Pi-Hole
    icon: mdi:block-helper
    url: !secret panel_iframe__pihole__url
