#-------------------------------------------
#  PiHole ad Blocking Related Packages
#
# See also:
#  https://github.com/Norien/Home-Assistant-Config/blob/624a59ebf45915f7e9a60853a3a7ea084175f4d3/packages/pihole.yaml
#-------------------------------------------
homeassistant:
  customize:
    sensor.pi_hole_version:
      friendly_name: Pi-Hole
      entity_picture: /local/custom_icons/pihole.png

    sensor.pi_hole_ads_percentage_today:
      friendly_name: Percentage of Ad Traffic Blocked
      unit_of_measurement: '%'
      icon: mdi:ticket-percent

    sensor.pi_hole_domains_being_blocked:
      friendly_name: Total Domains Blocking
      icon: mdi:do-not-disturb

    sensor.pi_hole_dns_unique_clients:
      friendly_name: Unique Clients
      icon: mdi:desktop-classic

    sensor.pi_hole_ads_blocked_today:
      friendly_name: Ads Blocked Today
      icon: mdi:do-not-disturb

    sensor.pi_hole_dns_queries_today:
      friendly_name: DNS Queries Today
      icon: mdi:note-text

    # sensor.carlopihole:
    #   friendly_name: Pi Hole Server
    #   icon: mdi:filter-variant

    switch.pihole_temp_disable:
      friendly_name: "Temp Disable"

    group.pihole:
      homebridge_hidden: true


#-------------------------------------------
sensor:
  - platform: pi_hole
    host: 192.168.0.5
    name: Pi Hole
    monitored_conditions:
      - dns_queries_today
      - ads_blocked_today
      - ads_percentage_today
      - ads_blocked_today
      - unique_clients

  - name: Uptime PiHole
    platform: mqtt
    state_topic: home/pihole/uptime/sec
    value_template: >-
      {# {% set value = 24 * 3600 + 0 * 60 * 60 + 20 * 60 %}#}
      {% set uptime = value | int %}
      {% set seconds = uptime % 60 %}
      {% set minutes = ((uptime % 3600) / 60) | int %}
      {% set hours = ((uptime % 86400) / 3600) | int %}
      {% set days = (uptime / 86400) | int %}
      {%- if days > 0 -%}
        {%- if days == 1 -%}
          1 day
        {%- else -%}
          {{ days }} days
        {%- endif -%}
        {{ ', ' }}
      {%- endif -%}
      {%- if hours > 0 -%}
        {%- if hours == 1 -%}
          1 h
        {%- else -%}
          {{ hours }} h
        {%- endif -%}
        {{ ' ' }}
      {%- endif -%}
      {%- if minutes > 0 -%}
        {%- if minutes == 1 -%}
          1 min
        {%- else -%}
          {{ minutes }} min
        {%- endif -%}
        {{ ' ' }}
      {%- endif -%}
      {%- if uptime < 5 * 60 -%}
        {%- if seconds == 1 -%}
          1 sec
        {%- elif seconds > 1 -%}
          {{ seconds }} sec
        {%- endif -%}
      {%- endif -%}

    
  - name: Temp PiHole
    platform: mqtt
    state_topic: "home/pihole/cpu/temp"
    unit_of_measurement: '°C'


# Pi-Hole switch
switch:
  - platform: command_line
    switches:
      pi_hole_temp_disable:
        command_on: "curl -X GET 'http://192.168.0.5/admin/api.php?enable&auth='"
        command_off: "curl -X GET 'http://192.168.0.5/admin/api.php?disable=3600&auth='"


binary_sensor:
  - platform: ping
    host: 192.168.0.5
    name: PiHole


#-------------------------------------------


group:
  pihole:
    name: Pi-Hole (ad-blocker)
    control: hidden
    entities:
      # - sensor.carlopihole
      - binary_sensor.pihole
      - sensor.pi_hole_version
      - sensor.uptime_pihole
      - sensor.temp_pihole
      - sensor.pi_hole_dns_unique_clients
      - sensor.pi_hole_dns_queries_today
      - sensor.pi_hole_ads_blocked_today
      - sensor.pi_hole_ads_percentage_today
      - sensor.pi_hole_ads_percentage_blocked_today
      - switch.pi_hole_temp_disable


#-------------------------------------------


        #panel_iframe:
        # pihole:
        # title: Pi-Hole
        #icon: mdi:block-helper
        #url: !secret panel_iframe__pihole__url
