#-------------------------------------------
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
#-------------------------------------------
# homeassistant:
#   customize:
#     sensor.process_mosquitto:
#       friendly_name: 'Mosquitto'
#
#       hidden: False

#-------------------------------------------
sensor:
  - platform: systemmonitor
    resources:
      # - type: last_boot
      - type: since_last_boot
      - type: disk_use_percent
        arg: /
      - type: disk_use_percent
        arg: /mnt/storage
        