sensor:
  - platform: sonarr
    api_key: !secret sensor_sonarr_api_key
    host: 192.168.0.10
    port: 32772
    monitored_conditions:
      - series
      - upcoming
      - diskspace
      - wanted
    days: 7

  - platform: radarr
    api_key: !secret sensor_radarr_api_key
    host: 192.168.0.10
    port: 32773
    monitored_conditions:
      - movies
      - upcoming
      - diskspace
      - status
    days: 7


  - name: Home Cinema UPS
    platform: nut
    host: 192.168.0.22
    port: 3493
    username: upsmon
    password: ups
    alias: ups
    resources:
      - battery.charge
      - battery.charge.low
      - battery.runtime
      - ups.beeper.status
      - ups.delay.shutdown
      - ups.load
      - ups.status.display
  
  - name: OSMC Uptime
    platform: mqtt
    state_topic: "home/osmc/uptime/sec"
    unit_of_measurement: 'sec'

  - name: OSMC Temperature
    platform: mqtt
    state_topic: "home/osmc/cpu/temp"
    unit_of_measurement: '°C'

  - platform: template
    sensors:
      osmc_uptime_templated:
        value_template: >-
          {%- set value = states('sensor.osmc_uptime').partition(' ')[0] -%}
          {# {% set value = 24 * 3600 + 0 * 60 * 60 + 20 * 60 %}#}
          {% set uptime = value | int %}
          {% set seconds = uptime % 60 %}
          {% set minutes = ((uptime % 3600) / 60) | int %}
          {% set hours = ((uptime % 86400) / 3600) | int %}
          {% set days = (uptime / 86400) | int %}
          {%- if days > 0 -%}
            {%- if days == 1 -%}
              1 day
            {%- else -%}
              {{ days }} days
            {%- endif -%}
            {{ ', ' }}
          {%- endif -%}
          {%- if hours > 0 -%}
            {%- if hours == 1 -%}
              1 h
            {%- else -%}
              {{ hours }} h
            {%- endif -%}
            {{ ' ' }}
          {%- endif -%}
          {%- if minutes > 0 -%}
            {%- if minutes == 1 -%}
              1 min
            {%- else -%}
              {{ minutes }} min
            {%- endif -%}
            {{ ' ' }}
          {%- endif -%}
          {%- if uptime < 5 * 60 -%}
            {%- if seconds == 1 -%}
              1 sec
            {%- elif seconds > 1 -%}
              {{ seconds }} sec
            {%- endif -%}
          {%- endif -%}

  - platform: template
    sensors:
      harmony_home_cinema_current_activity:
        value_template: '{{ states.remote.harmony_home_cinema.attributes.current_activity }}'
        friendly_name: 'Current Activity'


homeassistant:
  customize:
    sensor.osmc_uptime_templated:
      friendly_name: Since last boot
    remote.harmony_home_cinema:
      friendly_name: State


binary_sensor:
  - platform: ping
    host: 192.168.0.22
    name: osmc


media_player:
  - platform: kodi
    # name: "Home Cinema Salon Kodi"
    host: 192.168.0.20
    #username: gaetan
    #password: !secret media_player_kodi_password
  
  - platform: emby
    host: 192.168.0.10
    # name: "Emby"
    # id: emby
    port: 38096
    ssl: false
    api_key: !secret media_player_emby_api_key


remote:
  - platform: harmony
    name: Harmony Home Cinema
    host: 192.168.0.53

    
group:
  pvr:
    name: Smart PVR
    control: hidden
    entities:
      - sensor.radarr_movies
      - sensor.sonarr_upcoming
      - sensor.sonarr_series
      - sensor.sonarr_diskspace
      - media_player.emby_kodi_osmc_2
      - media_player.home_cinema_salon_kodi

  harmony:
    name: Harmony Home Cinema
    control: hidden
    entities:
      - remote.harmony_home_cinema
      - sensor.harmony_home_cinema_current_activity

  homecine_network:
    name: Home Cinema Information
    control: hidden
    entities:
      - binary_sensor.osmc
      - sensor.osmc_uptime_templated
      - sensor.osmc_temperature
      - sensor.home_cinema_ups_status
      - sensor.home_cinema_ups_battery_charge
      - sensor.home_cinema_ups_low_battery_setpoint
      - sensor.home_cinema_ups_ups_shutdown_delay
      - sensor.home_cinema_ups_battery_runtime
