camera:
  - platform: generic
    still_image_url: !secret camera__ip_1__still_picture_url
    name: "Camera IP 1"
    username: !secret camera__ip_1__username
    password: !secret camera__ip_1__password
    
  - platform: generic
    still_image_url: !secret camera__ip_2__still_picture_url
    name: "Camera IP 2"
    username: !secret camera__ip_2__username
    password: !secret camera__ip_2__password


#------------------------------------------------------------


binary_sensor:
  - platform: hikvision
    host: !secret camera__ip_1__ip
    name: "Cam 1"
    username: !secret camera__ip_1__username
    password: !secret camera__ip_1__password

  - platform: hikvision
    host: !secret camera__ip_2__ip
    name: "Cam 2"
    username: !secret camera__ip_2__username
    password: !secret camera__ip_2__password


#------------------------------------------------------------

    
group:
  surveillance:
    name: Surveillance
    control: hidden
    entities:
      - binary_sensor.camera_ip_1
      - camera.camera_ip_1

      - binary_sensor.camera_ip_2
      - camera.camera_ip_2
