camera:
  - platform: generic
    still_image_url: !secret camera__ip_1__still_picture_url
    name: "Camera IP 1"
    username: !secret camera__ip_1__username
    password: !secret camera__ip_1__password


#------------------------------------------------------------


binary_sensor:
  - platform: hikvision
    host: !secret camera__ip_1__ip
    name: Camera IP Entrance
    username: !secret camera__ip_1__username
    password: !secret camera__ip_1__password


#------------------------------------------------------------

    
group:
  surveillance:
    name: Surveillance
    entities:
      - binary_sensor.camera_ip_1
      - camera.camera_ip_1
