sensor:
  - platform: waze_travel_time
    name: "Gaetan's Work"
    origin: !secret sensor__waze_travel_time__home
    destination: '2 Avenue du Docteur Maurice Grynfogel, Toulouse'
    region: 'EU'
    
  - platform: waze_travel_time
    name: "Gaetan Back from Work"
    origin: '2 Avenue du Docteur Maurice Grynfogel, Toulouse'
    destination: !secret sensor__waze_travel_time__home
    region: 'EU'

  - platform: filter
    name: "Filtered Gaetan's Work"
    entity_id: sensor.gaetans_work
    filters:
      - filter: time_simple_moving_average
        window_size: 00:15
        precision: 2


  - platform: waze_travel_time
    name: "Aurelie's Work"
    origin: !secret sensor__waze_travel_time__home
    destination: "Hôpital Purpan, Place du Docteur Joseph Baylac, Toulouse"
    region: 'EU'
    
  - platform: waze_travel_time
    name: "Aurelie Back from Work"
    origin: "Hôpital Purpan, Place du Docteur Joseph Baylac, Toulouse"
    destination: !secret sensor__waze_travel_time__home
    region: 'EU'
    
  - platform: filter
    name: "Filtered Aurelie's Work"
    entity_id: sensor.aurelies_work
    filters:
      - filter: time_simple_moving_average
        window_size: 00:15
        precision: 2

history_graph:
  travel_time_to_aurelies_work:
    name: "Travel time to Aurelie's work"
    entities:
      - sensor.aurelies_work
      # - sensor.filtered_aurelies_work

  travel_time_to_gaetans_work:
    name: "Travel time to Gaetan's work"
    entities:
      - sensor.gaetans_work
      # - sensor.filtered_gaetans_work

group:
  travels:
    name: Travel times
    control: hidden
    entities:
      - sensor.aurelies_work
      - sensor.aurelie_back_from_work
      - sensor.gaetans_work
      - sensor.gaetan_back_from_work

  travel_details:
    name: Travel times details
    control: hidden
    entities:
      - sensor.aurelies_work
      - sensor.aurelie_back_from_work
      - history_graph.travel_time_to_aurelies_work
      - sensor.gaetans_work
      - sensor.gaetan_back_from_work
      - history_graph.travel_time_to_gaetans_work
