# From: 
#  https://philhawthorne.com/making-dumb-dishwashers-and-washing-machines-smart-alerts-when-the-dishes-and-clothes-are-cleaned/


input_select:
  washing_machine_status:
    name: Washing Machine Status
    options:
      - Idle
      - Running
      - Finished
      - Clean
    initial: Idle


automation:
  # When power is detected, and the washing machine is not in 
  # the Running state, change the status of the washing machine
  # to Running. 
  # The status check will ensure we don't try to put the state 
  # to Running each time the power level changes, and we're already
  # in the Running state.

  # When the power drops, move the state of the washin
  - alias: Set washing machine active when power detected
    trigger:
      - platform: numeric_state
        # entity_id: sensor.washing_machine_power
        entity_id: sensor.washing_machine_energy_each_2_min
        above: 8
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: sensor.washing_machine_status
          state: Idle
        - condition: state
          entity_id: sensor.washing_machine_status
          state: Clean
        - condition: state
          entity_id: sensor.washing_machine_status
          state: Finished
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: Running
      - service: notify.pushover
        data:
          message: 'Washing Machine is running'
          title: 'Washing Machine Update'
  
  # When the power drops, move the state of the washing machine to Clean.
  - alias: Set washing machine finished when power drops
    trigger:
      - platform: numeric_state
        # entity_id: sensor.washing_machine_power
        entity_id: sensor.washing_machine_energy_each_2_min
        above: 0.5
        below: 2
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: input_select.washing_machine_status
          state: Idle
        - condition: state
          entity_id: input_select.washing_machine_status
          state: Running
        - condition: state
          entity_id: input_select.washing_machine_status
          state: Finished
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: Clean
      - service: notify.pushover
        data:
          message: 'Washing Machine is finishing'
          title: 'Washing Machine Update'

  # When the power drops, move the state of the washing machine to Clean.
  - alias: Set washing machine finished when power drops
    trigger:
      - platform: numeric_state
        # entity_id: sensor.washing_machine_power
        entity_id: sensor.washing_machine_energy_each_2_min
        below: 0.4
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: input_select.washing_machine_status
          state: Running
        - condition: state
          entity_id: input_select.washing_machine_status
          state: Finished
        - condition: state
          entity_id: input_select.washing_machine_status
          state: Clean
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: Idle

  # 
  # # When we open the washing machine door, reset the status back to
  # # idle, so we don't spam people that the washing machine has 
  # # finished, and someone has already emptied it
  # - alias: Set washing machine dirty when door opens
  #   trigger:
  #     # I've setup a template sensor to change make the binary_sensor report open and closed
  #     # instead of 1 and 0
  #     - platform: state
  #       entity_id: input_select.washingmachine_door_status
  #       to: 'Open'
  #   condition:
  #     condition: and
  #     conditions:
  #       - condition: state
  #         entity_id: input_select.washing_machine_status
  #         state: Clean
  #   action:
  #     - service: input_select.select_option
  #       data:
  #         entity_id: input_select.washing_machine_status
  #        option: Idle

  - alias: Send alert when washing machine is clean
    trigger:
      - platform: state
        entity_id: input_select.washing_machine_status
        to: Clean
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.washing_machine_status
          state: Clean
    action:
      - service: notify.pushover
        data:
          message: 'The Washing Machine has finished and is ready to be emptied!'
          title: 'Washing Machine Update'


sensor:
  - platform: template
    sensors:
      washing_machine_status:
        value_template: '{{ states.input_select.washing_machine_status.state}}'
        friendly_name: 'Washing Machine Status'

  - platform: statistics
    entity_id: sensor.washing_machine_power
    name: "Washing Machine Energy each 10 samples"
    sampling_size: 10

  - platform: filter
    name: "Washing Machine Energy each 2 min"
    entity_id: sensor.washing_machine_power
    filters:
      - filter: time_simple_moving_average
        window_size: 00:02
        precision: 2

homeassistant:
  customize:
    sensor.washing_machine_status:
      icon: mdi:washing-machine
    input_select.washing_machine_status:
      persistent: true
    sensor.washing_machine_energy_each_2_min:
      persistent: true
      friendly_name: "Washing Machine Energy (2 min moving average)"


group:
  washing_machine:
    name: Washing Machine
    entities:
      - sensor.washing_machine_status
      - sensor.washing_machine_energy_each_2_min
