# From: 
#  https://philhawthorne.com/making-dumb-dishwashers-and-washing-machines-smart-alerts-when-the-dishes-and-clothes-are-cleaned/

# (pwr < 0.2)
#  |
#  |
# Stopped    ---->-----\
#  |                   |
#  | (2 < pwr < 12)    |
#  |                   |
# Idle                 |
#  |                   |
#  | ( pwr > 12)       |
#  |                   | <------\
# Running  <-----------/        |
#  |                            |
#  | ( 0.2 < pwr < 2)           | ( pwr > 12)  
#  |                            |
# Finished ---->--------->------/
#  |
#  | ( < 0.2)
#  |
# Stopped


input_select:
  washing_machine_status:
    name: Washing Machine Status
    options:
      - Stopped
      - Idle
      - Running
      - Finished
    initial: Stopped


automation:

  # When the power is very low or null, reset it to Stopped
  - alias: Set washing machine finished when power drops
    trigger:
      - platform: numeric_state
        # entity_id: sensor.washing_machine_power
        entity_id: sensor.washing_machine_energy_each_2_min
        below: 0.4
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: Stopped

  # When the power is not null but not too high, it is probably the
  # idle time. Set it to Idle
  - alias: Set washing machine finished when power drops
    trigger:
      - platform: numeric_state
        # entity_id: sensor.washing_machine_power
        entity_id: sensor.washing_machine_energy_each_2_min
        above: 2
        below: 12
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: input_select.washing_machine_status
          state: Stopped
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: Idle
      - service: notify.pushover
        data:
          message: 'Washing Machine is idle'
          title: 'Washing Machine Update'


  - alias: Set washing machine active when power detected
    trigger:
      - platform: numeric_state
        # entity_id: sensor.washing_machine_power
        entity_id: sensor.washing_machine_energy_each_2_min
        above: 12
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: sensor.washing_machine_status
          state: Stopped
        - condition: state
          entity_id: sensor.washing_machine_status
          state: Idle
        - condition: state
          entity_id: sensor.washing_machine_status
          state: Clean
        - condition: state
          entity_id: sensor.washing_machine_status
          state: Finished
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: Running
      - service: notify.pushover
        data:
          message: 'Washing Machine is running'
          title: 'Washing Machine Update'
  
  # When the power drops, move the state of the washing machine to Clean.
  - alias: Set washing machine finished when power drops
    trigger:
      - platform: numeric_state
        # entity_id: sensor.washing_machine_power
        entity_id: sensor.washing_machine_energy_each_2_min
        above: 0.2
        below: 2
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: input_select.washing_machine_status
          state: Running
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: Finished
      - service: notify.pushover
        data:
          message: 'Washing Machine is finishing'
          title: 'Washing Machine Update'

  - alias: Send alert when washing machine is clean
    trigger:
      - platform: state
        entity_id: input_select.washing_machine_status
        to: Finished
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.washing_machine_status
          state: Running
    action:
      - service: notify.pushover
        data:
          message: 'The Washing Machine has finished and is ready to be emptied!'
          title: 'Washing Machine Update'


sensor:
  - platform: template
    sensors:
      washing_machine_status:
        value_template: '{{ states.input_select.washing_machine_status.state}}'
        friendly_name: 'Washing Machine Status'

  - platform: statistics
    entity_id: sensor.washing_machine_power
    name: "Washing Machine Energy each 10 samples"
    sampling_size: 10

  - platform: filter
    name: "Washing Machine Energy each 2 min"
    # entity_id: sensor.washing_machine_power
    entity_id: sensor.washing_machine_smart_plug_power
    filters:
      - filter: time_simple_moving_average
        window_size: 00:02
        precision: 2

homeassistant:
  customize:
    sensor.washing_machine_status:
      icon: mdi:washing-machine
    input_select.washing_machine_status:
      persistent: true
    sensor.washing_machine_energy_each_2_min:
      persistent: true
      friendly_name: "Washing Machine Energy (2 min moving average)"


group:
  washing_machine:
    name: Washing Machine
    entities:
      - sensor.washing_machine_status
      - sensor.washing_machine_energy_each_2_min
