automation:
  - alias: Recycle Container Warning
    trigger:
      platform: time
      at: '19:00:00'
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - tue
    action:
      - service: notify.pushover
        data:
          message: "Do not forget to take out the yellow bin!"


  - alias: Waste Container Warning
    trigger:
      platform: time
      at: '19:00:00'
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - thu
    action:
      - service: notify.pushover
        data:
          message: "Do not forget to take out the green bin!"
