sensor:
  - platform: yr
    name: Weather
    forecast: 1
    monitored_conditions:
      - cloudiness
      - dewpointTemperature
      - fog
      - highClouds
      - humidity
      - lowClouds
      - mediumClouds
      - precipitation
      - pressure
      - symbol
      - temperature
      - windDirection
      - windSpeed

  - platform: yr
    name: Forecast 6h
    forecast: 6
    monitored_conditions:
      - cloudiness
      - precipitation
      - pressure
      - symbol
      - temperature
      - windSpeed
  
  - platform: yr
    name: Forecast 24h
    forecast: 24
    monitored_conditions:
      - cloudiness
      - precipitation
      - pressure
      - symbol
      - temperature
      - windSpeed

  - platform: wunderground
    api_key: !secret sensor__wunderground__api_key
    monitored_conditions:
      - alerts
      - dewpoint_c

group:
  current:
    name: Actuel
    entities:
      - sensor.season
      - sensor.date
      - sensor.time
      - sensor.time_utc
      - sun.sun

  weather_1h:
    name: Metéo 1h
    entities:
      - sensor.weather_symbol
      - sensor.weather_temperature
      - sensor.weather_precipitation
      - sensor.weather_pressure
      - sensor.weather_wind_speed
      - sensor.weather_cloudiness
      - sensor.pws_alerts
      - sensor.pws_dewpoint_c
      - sensor.weather_dewpoint_temperature
      - sensor.weather_fog
      - sensor.weather_high_clouds
      - sensor.weather_humidity
      - sensor.weather_low_clouds
      - sensor.weather_medium_clouds
      - sensor.weather_wind_direction

  forecast_6h:
    name: Prevision 6h
    entities:
      - sensor.forecast_6h_symbol
      - sensor.forecast_6h_temperature
      - sensor.forecast_6h_precipitation
      - sensor.forecast_6h_pressure
      - sensor.forecast_6h_wind_speed
      - sensor.forecast_6h_cloudiness

  forecast_24h:
    name: Prevision 24h
    entities:
      - sensor.forecast_24h_symbol
      - sensor.forecast_24h_temperature
      - sensor.forecast_24h_precipitation
      - sensor.forecast_24h_pressure
      - sensor.forecast_24h_wind_speed
      - sensor.forecast_24h_cloudiness
  